development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_AUDIENCE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_AUDIENCE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_AUDIENCE"] %>
